language: python
install:
  - pip install tox
script:
  - tox
notifications:
  slack:
    secure: b8NV8DYDDGosQ4E5c/dzEcrgORd7aALf80n57Zcr6VpaosslzVTygb+9DkT2y1gMQdrJE09KVHe/Er0hJcNoqXQ2wfdrQ5Dek5sKXWAOGYp66OB9ZONpkeDQ54VijfHiWl/1sEnDbpGUOyYeQt8T4F0oGApetvzkF4+q4TeCpNBrYlwDT1EBs+EiDAwex+9H6gGhAXD1UqdiqXL4/qATGeKcLcPFI/JvJS2T1oHTqiMC1d4HLE3mv9ZDT1hn3ytDG1NsGWa5DSp08fiVEkrp4joBAm1the20BbN91uiFlT95ZCtDkpUXv7+x4gduHzUPJueyAh1GaVmv1l+efCP3kDBqPKjOFBKauY6q/m90z2vM0r4GU4VY0JILG4BNbwoNBoDlrp90QwbFAEVW23ZpCMi4eTtxywtynetFXeHaEb1QuTpABULldv4BZE3dKDefChzLBdtThWv9VReRGG6mWjrxpYxuMO8vJYN7BkcRCFj2jNiGEEXLSv3fX06b3fT0oUBf5Whenl5wNe1LPblrtKwU0woq6f6aA7ONVbCYr9KrFkGfqjYevMjc/SgVsqYPJqeg+RzUevle6voPNkJ+lIgiY+XOMh+kr0XJwDOx3YFTluw/xV5hx+IXyyFGDPL7WNUIgoyRuD0MbsWnCMKoQS8NBqFVDw6/VS1RHX3o0bQ=
    on_start: always
    on_failure: always
    on_success: always
